[package]
name = "midimon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.7.0"
argparse = "0.2.2"
fuzzy-matcher = "*"
termsize = "0.1"
termion = "1.5.6"

[features]
debug = []
